# 配置站点
title: '耀庄的博客'
description: '珍惜今下的阳光，做回之前做的事。<br> 再来看看我的文章，我们都是游戏好友而已！'
keyword: 'minecraft / 科技 / html / 尝试'
url: 'https://sunbertrs.github.io/sunbossrs-blog-v1' # your host

# 基层路径
baseurl: ''

# 页面背景填充
Tickbg: '/assets/img-lib/dark-tickbg.jpg'

# 博客图床设置链接
imgbed: 'https://coding.net/u/SunbossRS/p/GotBlogDowner/git/raw/master'

# 导航
nav:
  主页: '/'
  标签: '/tags.html'
  网站信息: '/Pages/Information.html'
  友链: '/Pages/links.html'
  关于我: '/Pages/AboutMe.html'
  下载站: '/MyDownloadStation/index.html'

# 底部信息
footer:
  since: 2016
  say: '庄主一出手，就知有没有!'

# 配置博主信息
author: '耀日庄主'
nickname: 'SunbossRS'
bio: '一名MC主UP主实况主技术主博客主世界主 _'
avatar: '/assets/img-lib/profile-avatar.jpg'

# 搜索功能
search: true

# 夜间模式
nightMode: true

# 回到顶部按钮 by ray-eldath
b2t: true

# 评论功能
comments:
  # 使用disqus评论器 by liaokeyu
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'

  # 使用gitalk评论器 by tea9
  gitalk: true
  gitalk_clientID: '800a929ad18c8e90fdbc'
  gitalk_Secret: '3dcb1cc3680b9b85ad4291367b4aafefd6806e58'
  gitalk_repo: 'SunTalk_Save'
  gitalk_owner: 'SunbossRS'
  gitalk_admin: 'SunbossRS'
  distractionFreeMode: true
  
  # 使用livere评论器 by ray-eldath
  livere: false
  
# MathJax公式支持 by Ray-Eldath
mathjax: false

# 分享功能
social-share: true

# 主题皮肤
theme-color: 'pink'  # pink or default

# 赞赏
reward: 
  enable: true

# 选择背景样板
postPatterns: 'circuitBoard'

# 设置标签
recommend-tags: true  # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# 建站设置
paginate: 7
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# 配置社交网站SNS
#支持 email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: '//github.com/sunbossrs'
  email: '//yaorizhuangzhu@163.com'
  twitter: '//twitter.com/mcsunboss'

# Markdown编译器设置
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  enable_codetray:  true

# RSS订阅
RSS: false

# 文章网站格式
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins 
plugins: [jekyll-paginate]
